---
Name: iconpicker-config
---
NobrainerWeb\IconPicker\ORM\Icon:
  cms_icon_source_folder: 'public/images/icons/material/SVG'
  template_icon_source_folder: 'public/images/icons/material/SVG'
  all_icons_file: 'public/images/icons/material/demo.html' # local html page
